repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
      - id: check-toml
      - id: name-tests-test
        args: [--unittest]
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: make-format
        name: Format Code
        entry: make format
        language: system
        types: [python]
      - id: make-lint
        name: Lint Code
        entry: make lint
        language: system
        types: [python]
      - id: make-test
        name: Test Code w/ Coverage
        entry: make test
        language: system
        types: [python]
